import localFont from "next/font/local";
import "./globals.css";




export const metadata = {
  title: "fondo haloween",
  description: "Generated by nextjs and Cloudinary",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
